// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-YXgHVCxKszCCrq9j73S-nWT7UnblhWE',
    appId: '1:35980838996:web:98d337e736aa93eba305c1',
    messagingSenderId: '35980838996',
    projectId: 'echoalert-a06e6',
    authDomain: 'echoalert-a06e6.firebaseapp.com',
    storageBucket: 'echoalert-a06e6.firebasestorage.app',
    measurementId: 'G-WWEVX2XR4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_b0Zj2SvCocU95MZFm64mqha60RuEBiQ',
    appId: '1:35980838996:android:30ac336e746af533a305c1',
    messagingSenderId: '35980838996',
    projectId: 'echoalert-a06e6',
    storageBucket: 'echoalert-a06e6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOebLOSdh0mpCR83fVrzUZXbjWS_GWz8',
    appId: '1:35980838996:ios:69ac50017656d83da305c1',
    messagingSenderId: '35980838996',
    projectId: 'echoalert-a06e6',
    storageBucket: 'echoalert-a06e6.firebasestorage.app',
    iosBundleId: 'com.example.sos1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOebLOSdh0mpCR83fVrzUZXbjWS_GWz8',
    appId: '1:35980838996:ios:69ac50017656d83da305c1',
    messagingSenderId: '35980838996',
    projectId: 'echoalert-a06e6',
    storageBucket: 'echoalert-a06e6.firebasestorage.app',
    iosBundleId: 'com.example.sos1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-YXgHVCxKszCCrq9j73S-nWT7UnblhWE',
    appId: '1:35980838996:web:16f4f9a7ade00d56a305c1',
    messagingSenderId: '35980838996',
    projectId: 'echoalert-a06e6',
    authDomain: 'echoalert-a06e6.firebaseapp.com',
    storageBucket: 'echoalert-a06e6.firebasestorage.app',
    measurementId: 'G-39WQ8LRSM4',
  );
}
