import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'Francais';

  String get currentLanguage => _currentLanguage;

  // Your translations map
  final translations = {
    'Francais': {
      'back': 'Retour',
      'save': 'Sauvgarder',
      'life_critical_emergency_service': 'SERVICE D\'URGENCE CIVILE',
      'Algerian_Democratic_and_Popular_Republic': 'RÉPUBLIQUE ALGÉRIENNE DÉMOCRATIQUE ET POPULAIRE',
      'app_name': 'SOS ALGÉRIE',
      'language': 'LANGAGE',
      'selected': 'SÉLECTIONNÉ',
      'french': 'Français',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'Paramètres',
      'home': 'Accueil',
      'profile': 'Profil',
      'about': 'À propos',
      'help': 'Aide',
      'logout': 'Déconnexion',
      'next': 'Suivant',
      'account_security': 'COMPTE ET SÉCURITÉ',
      'app_preferences': 'PRÉFÉRENCES APPLICATION',
      'medical_profile': 'Profil Médical',
      'medical_profile_subtitle': 'Groupe sanguin, allergies...',
      'emergency_contacts': 'Contacts d\'Urgence',
      'emergency_contacts_subtitle': 'Personnes à prévenir',
      'language_subtitle': 'Sélection(Français/English/العربية)',
      'location_sharing': 'Partage de Localisation (SMS)',
      'location_sharing_subtitle': 'Envoi automatique du GPS',
      'sos_history': 'Historique des SOS',
      'sos_history_subtitle': 'Consulter les alertes passées',
      'emergency_number': "Numéro d'urgence",
      'ai_used': "IA Utilisé",
      'emergency_mode_activated': 'Lancement du mode urgence...',
      'modify': 'Modifier',
      'vital_information': 'Informations Vitales',
      'rapid_calls':'APPELS RAPIDES',
      'how_can_i_help':'Comment puis-je vous aider ?',
      'voice_assistant_active':'ASSISTANT VOCAL ACTIF',
      'example': '"J\'ai besoin d\'une ambulance à Alger Centre, une personne est inconsciente..."',
      'samu':'SAMU',
      'police':'Police',
      'fire_department':'Pompiers',
      'listening': 'Je vous écoute...',
      'helpIsComing':'L\'aide est en route.',
      'emergencyDetected':'Urgence détectée !',
      'processing':'Traitement en cours...',
      'fire_emergency':'Urgence Incendie',
      'police_emergency':'Urgence Police',
      'medical_emergency':'Urgence Médicale',
      'please_try_again':'Veuillez réessayer',
      'speech_not_available':'Reconnaissance vocale non disponible',
      'mic_permission_denied':'Permission microphone refusée',
      'ai_processing':'Analyse IA en cours...',
      'app_subtitle':'Assistant IA',
    },
    'العربية': {
      'back': 'عودة',
      'save': 'حفظ',
      'life_critical_emergency_service': 'خدمة الطوارئ',
      'Algerian_Democratic_and_Popular_Republic': 'الجمهورية الجزائرية الديمقراطية الشعبية',
      'app_name': 'SOS الجزائر',
      'language': 'اللغة',
      'selected': 'تم اختياره',
      'french': 'Français',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'الإعدادات',
      'home': 'الرئيسية',
      'profile': 'الملف الشخصي',
      'about': 'حول',
      'help': 'مساعدة',
      'logout': 'تسجيل الخروج',
      'next': 'التالي',
      'account_security': 'الحساب والأمان',
      'app_preferences': 'تفضيلات التطبيق',
      'medical_profile': 'الملف الطبي',
      'medical_profile_subtitle': 'فصيلة الدم، الحساسية...',
      'emergency_contacts': 'جهات الاتصال للطوارئ',
      'emergency_contacts_subtitle': 'الأشخاص الذين يجب إخطارهم',
      'language_subtitle': 'اختيار(Français/English/العربية)',
      'location_sharing': 'مشاركة الموقع (SMS)',
      'location_sharing_subtitle': 'إرسال GPS تلقائي',
      'sos_history': 'سجل SOS',
      'sos_history_subtitle': 'عرض التنبيهات السابقة',
      'emergency_number': 'رقم الطوارئ',
      'ai_used': "تم استخدام الذكاء الاصطناعي",
      'emergency_mode_activated': 'تم تفعيل وضع الطوارئ...',
      'modify': 'تعدبل',
      'vital_information': 'معلومات حيوية',
      'rapid_calls':'اتصالات السريعة',
      'how_can_i_help':'كيف يمكنني مساعدتك؟',
      'voice_assistant_active':'مساعد صوتي نشط',
      'example': '"أحتاج سيارة إسعاف في وسط الجزائر، شخص ما فاقد للوعي..."',
      'samu':'الحماية المدنية',
      'police':'الشرطة',
      'fire_department':'رجال الإطفاء',
      'listening': 'أنا أستمع...',
      'help_is_coming':'L\'aide est en route.',
      'emergency_detected':'Urgence détectée !',
      'processing':'Traitement en cours...',
      'fire_emergency':'حالة طوارئ حريق',
      'police_emergency':'حالة طوارئ شرطية',
      'medical_emergency':'حالة طوارئ طبية',
      'please_try_again':'يرجى المحاولة مرة أخرى',
      'speech_not_available':'التعرف على الكلام غير متاح',
      'mic_permission_denied':'تم رفض إذن استخدام الميكروفون',
      'ai_processing':'تحليل الذكاء الاصطناعي قيد التقدم...',
      'app_subtitle':'مساعد IA',
    },
    'English': {
      'back': 'Back',
      'save': 'Save',
      'life_critical_emergency_service': 'LIFE-CRITICAL EMERGENCY SERVICE',
      'Algerian_Democratic_and_Popular_Republic': 'ALGERIAN DEMOCRATIC AND POPULAR REPUBLIC',
      'app_name': 'SOS ALGERIA',
      'selected': 'SELECTED',
      'french': 'Français',
      'arabic': 'العربية',
      'english': 'English',
      'settings': 'Settings',
      'home': 'Home',
      'profile': 'Profile',
      'about': 'About',
      'help': 'Help',
      'logout': 'Logout',
      'next': 'Next',
      'account_security': 'ACCOUNT & SECURITY',
      'app_preferences': 'APP PREFERENCES',
      'medical_profile': 'Medical Profile',
      'medical_profile_subtitle': 'Blood type, allergies...',
      'emergency_contacts': 'Emergency Contacts',
      'emergency_contacts_subtitle': 'People to notify',
      'language': 'Language',
      'language_subtitle': 'Selection(Français/English/العربية)',
      'location_sharing': 'Location Sharing (SMS)',
      'location_sharing_subtitle': 'Automatic GPS sending',
      'sos_history': 'SOS History',
      'sos_history_subtitle': 'View past alerts',
      'emergency_number': 'Emergency number',
      'ai_used': "AI Used",
      'emergency_mode_activated': 'Emergency mode activated...',
      'modify': 'Modify',
      'vital_information': 'Vital Information',
      'rapid_calls':'RAPID CALLS',
      'how_can_i_help':'How can I help you ?',
      'voice_assistant_active':'ACTIVE VOICE ASSISTANT',
      'example': '"I need an ambulance in Algiers Centre, someone is unconscious..."',
      'samu':'Emergency Medical Services',
      'police':'Police',
      'fire_department':'Fire Department',
      'listening': 'I am listening...',
      'helpIsComing':'Help is on the way',
      'emergencyDetected':'Emergency Detected !',
      'processing':'Traitement en cours...',
      'fire_emergency':'fire Emergency',
      'police_emergency':'police Emergency',
      'medical_emergency':'medical Emergency',
      'please_try_again':'Please try again',
      'speech_not_available':'Speech recognition not available',
      'mic_permission_denied':'Microphone permission denied',
      'ai_processing':'AI Processing...',
      'app_subtitle':'AI Assistant',
    },
  };

  // Load saved language from storage
  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('selected_language') ?? 'Francais';
    notifyListeners();
  }

  // Change language and save to storage
  Future<void> setLanguage(String language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('selected_language', language);
    notifyListeners(); // This updates all widgets listening
  }

  // Get translated text
  String translate(String key) {
    return translations[_currentLanguage]?[key] ?? key;
  }

  // Helper to check if current language is RTL
  bool get isRTL => _currentLanguage == 'العربية';
}